### ISSUE TITLE
Docker compose healthcheck for VTN is broken

### ISSUE THREAD

**Issue by pohlm01** [OpenLEADR/openleadr-rs#45]
The health check in the docker compose for the VTN is broken, since it tries connecting to the `/programs` route, which requires authentication meanwhile.
To fix that, we should add a simple route to the backend (something like `/healthy` or `/healthcheck`), which responds with an appropriate HTTP status code and does not require authentication. If possible, this route should check, if the DB connection is available.

**Comment by KeeganMyers** [comment]
PR https://github.com/OpenLEADR/openleadr-rs/pull/50 should address this
